import { existsSync, readFileSync } from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { basename, join } from 'node:path';

import {
  MARKETPLACE_DISPLAY_NAME,
  MARKETPLACE_NAME,
  REPOSITORY,
  ROOT,
  listDirs,
  readJSON as readJSONFile,
} from '../scripts/lib.mjs';

function readJSON(path) {
  return readJSONFile(join(ROOT, path));
}

test('codex marketplace mirrors the Claude marketplace', () => {
  const claudeMarketplace = readJSON('.claude-plugin/marketplace.json');
  const codexMarketplace = readJSON('.agents/plugins/marketplace.json');

  assert.equal(codexMarketplace.name, MARKETPLACE_NAME);
  assert.equal(codexMarketplace.interface.displayName, MARKETPLACE_DISPLAY_NAME);
  assert.deepEqual(
    codexMarketplace.plugins.map((plugin) => plugin.name),
    claudeMarketplace.plugins.map((plugin) => plugin.name),
  );

  for (const plugin of codexMarketplace.plugins) {
    const claudePlugin = claudeMarketplace.plugins.find((item) => item.name === plugin.name);

    assert.equal(plugin.source.source, 'local');
    assert.equal(plugin.source.path, claudePlugin.source);
    assert.equal(plugin.policy.installation, 'AVAILABLE');
    assert.equal(plugin.policy.authentication, 'ON_INSTALL');
    assert.equal(plugin.category, 'Legal');
  }
});

test('each Claude plugin has an equivalent Codex plugin manifest', () => {
  const marketplace = readJSON('.claude-plugin/marketplace.json');

  for (const entry of marketplace.plugins) {
    const pluginRoot = entry.source.replace(/^\.\//, '');
    const claudeManifest = readJSON(`${pluginRoot}/.claude-plugin/plugin.json`);
    const codexManifest = readJSON(`${pluginRoot}/.codex-plugin/plugin.json`);

    assert.equal(codexManifest.name, claudeManifest.name);
    assert.equal(codexManifest.version, claudeManifest.version);
    assert.equal(codexManifest.description, claudeManifest.description);
    assert.deepEqual(codexManifest.author, claudeManifest.author);
    assert.equal(codexManifest.skills, './skills/');
    assert.equal(codexManifest.repository, REPOSITORY);
    assert.equal(codexManifest.license, 'MIT');
    assert.equal(codexManifest.interface.displayName, entry.displayName);
    assert.equal(codexManifest.interface.developerName, entry.author.name);
    assert.equal(codexManifest.interface.category, 'Legal');
    assert.ok(Array.isArray(codexManifest.interface.defaultPrompt));
    assert.ok(codexManifest.interface.defaultPrompt.length > 0);
    assert.ok(codexManifest.interface.shortDescription.length <= 160);

    if (existsSync(join(ROOT, pluginRoot, '.mcp.json'))) {
      assert.deepEqual(codexManifest.interface.capabilities, ['Skills', 'MCP']);
      assert.equal(codexManifest.mcpServers, './.mcp.json');

      const claudeMcp = readJSON(`${pluginRoot}/.mcp.json`);
      const codexMcpSidecar = join(ROOT, pluginRoot, '.codex-plugin/mcp.json');

      assert.equal(typeof claudeMcp.mcpServers, 'object');
      assert.equal(existsSync(codexMcpSidecar), false);
    } else {
      assert.deepEqual(codexManifest.interface.capabilities, ['Skills']);
      assert.equal(codexManifest.mcpServers, undefined);
    }
  }
});

test('codex repo guidance and setup docs exist', () => {
  assert.ok(existsSync(join(ROOT, 'CODEX.md')));
});

// Käy läpi KAIKKI generoidut agents/openai.yaml-tiedostot marketplacesta
// johdettuna — uudet skillit saavat kattavuuden automaattisesti ilman
// käsin listattuja polkuja.
test('every generated openai.yaml is structurally valid and matches its plugin .mcp.json', () => {
  const marketplace = readJSON('.claude-plugin/marketplace.json');
  let generatedCount = 0;

  for (const entry of marketplace.plugins) {
    const pluginRoot = entry.source.replace(/^\.\//, '');
    const hasMcp = existsSync(join(ROOT, pluginRoot, '.mcp.json'));
    const servers = hasMcp ? readJSON(`${pluginRoot}/.mcp.json`).mcpServers : {};

    for (const skillDir of listDirs(join(ROOT, pluginRoot, 'skills'))) {
      const yamlPath = join(skillDir, 'agents', 'openai.yaml');
      if (!existsSync(yamlPath)) continue;
      generatedCount += 1;

      const where = `${pluginRoot}/skills/${basename(skillDir)}/agents/openai.yaml`;
      assert.ok(hasMcp, `${where}: openai.yaml plugarissa, jolla ei ole .mcp.json-tiedostoa`);

      const text = readFileSync(yamlPath, 'utf8');
      assert.match(text, /^# Generated by scripts\/generate-codex\.mjs/, `${where}: generointiotsake puuttuu`);
      assert.match(text, /interface:/, where);
      assert.match(text, /display_name:\s+"/, where);
      assert.match(text, /short_description:\s+"/, where);

      const blocks = text.split(/^ {4}- type: "mcp"$/m).slice(1);
      assert.ok(blocks.length > 0, `${where}: ei yhtään työkaluriippuvuutta`);

      for (const block of blocks) {
        const name = block.match(/value:\s+"([^"]+)"/)?.[1];
        assert.ok(name, `${where}: riippuvuudelta puuttuu value`);
        const server = servers[name];
        assert.ok(server, `${where}: riippuvuus '${name}' puuttuu plugarin .mcp.json:sta`);

        if (server.url) {
          assert.match(block, /transport:\s+"streamable_http"/, `${where}: ${name}`);
          assert.ok(block.includes(`url: "${server.url}"`), `${where}: ${name}: url ei vastaa .mcp.json:ia`);
        } else {
          assert.match(block, /transport:\s+"stdio"/, `${where}: ${name}`);
          assert.ok(block.includes(`command: "${server.command}"`), `${where}: ${name}: command ei vastaa .mcp.json:ia`);
        }
      }
    }
  }

  assert.ok(generatedCount > 0, 'yhtään generoitua openai.yaml-tiedostoa ei löytynyt');
});

// Tarkoitusankkurit: nämä skillit EDELLYTTÄVÄT kyseisiä työkaluriippuvuuksia.
// Rakennetesti yllä ei huomaa, jos tunnistus lakkaa löytämästä riippuvuutta
// (tiedosto vain katoaa) — tämä taulu huomaa. Uusi kriittinen skilli: lisää rivi.
const EXPECTED_DEPENDENCIES = {
  'juristi/skills/oikeustutkimus': ['oik-ai'],
  'sopimukset/skills/sopimuksen-tarkistus': ['adeu', 'oik-ai'],
  'tekoalysaantely/skills/tekoaly-velvoitteet': ['eu-ai-act'],
  'julkiset-hankinnat/skills/tarjouspyynto-ja-tarjous': ['oik-ai'],
  'yhtiooikeus/skills/osakassopimus': ['adeu', 'oik-ai'],
  // lähdevarmistuksen luovutuspisteet
  'insolvenssi/skills/saatavien-perinta': ['oik-ai'],
  'lainvalmistelu/skills/lainkirjoittajan-opas': ['oik-ai'],
  'tekoalysaantely/skills/tekoaly-vaatimustenmukaisuus': ['eu-ai-act', 'oik-ai'],
};

test('mcp-dependent skills declare Codex tool dependencies', () => {
  for (const [skillPath, expected] of Object.entries(EXPECTED_DEPENDENCIES)) {
    const yamlPath = join(ROOT, skillPath, 'agents', 'openai.yaml');
    assert.ok(
      existsSync(yamlPath),
      `${skillPath}: agents/openai.yaml puuttuu — onko skilli siirretty tai riippuvuustunnistus rikki?`,
    );
    const text = readFileSync(yamlPath, 'utf8');
    for (const dependency of expected) {
      assert.match(
        text,
        new RegExp(`value:\\s+"${dependency}"`),
        `${skillPath}: odotettu riippuvuus '${dependency}' puuttuu`,
      );
    }
  }
});

// Nämä skillit eivät saa MCP-riippuvuuksia, vaikka teksti sivuaa oikeuslähteitä.
const FORBIDDEN_GENERATED_METADATA = [
  'juristi/skills/kaytantoprofiili',
  'juristi/skills/suomen-kieli',
];

test('skills without MCP dependencies do not retain stale generated metadata', () => {
  for (const skillPath of FORBIDDEN_GENERATED_METADATA) {
    const yamlPath = join(ROOT, skillPath, 'agents', 'openai.yaml');
    assert.equal(existsSync(yamlPath), false, `${skillPath}: odottamaton generoitu openai.yaml`);
  }
});

test('workflows run the shared generated-files check', () => {
  for (const workflow of ['.github/workflows/validate.yml', '.github/workflows/release.yml']) {
    const text = readFileSync(join(ROOT, workflow), 'utf8');
    assert.match(text, /scripts\/check-generated\.sh/, `${workflow}: yhteinen drift-tarkistus puuttuu`);
  }

  const script = readFileSync(join(ROOT, 'scripts/check-generated.sh'), 'utf8');
  assert.match(script, /generate-skills-md\.mjs/);
  assert.match(script, /generate-codex\.mjs/);
  assert.match(script, /git ls-files --others --exclude-standard/);
  assert.match(script, /Codex-generointi loi commitista puuttuvia tiedostoja/);
  assert.match(script, /\*\/skills\/\*\/agents\/openai\.yaml/);
  assert.match(script, /\*\/\.codex-plugin\/plugin\.json/);
});
