import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
import assert from 'node:assert/strict';
import { dirname, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function copyRepoFixture() {
  const fixtureRoot = mkdtempSync(join(tmpdir(), 'legal-for-finland-'));
  cpSync(ROOT, fixtureRoot, {
    recursive: true,
    filter: (source) => {
      const normalized = source.replace(/\\/g, '/');
      return !normalized.endsWith('/.git') && !normalized.includes('/node_modules/');
    },
  });
  return fixtureRoot;
}

function runNodeScript(script, cwd) {
  return spawnSync(process.execPath, [script], {
    cwd,
    encoding: 'utf8',
  });
}

function normalizeEol(text) {
  return text.replace(/\r\n/g, '\n');
}

test('validate script accepts repository paths and CRLF frontmatter on Windows', () => {
  const fixtureRoot = copyRepoFixture();

  try {
    const skillPath = join(fixtureRoot, 'juristi/skills/juristi/SKILL.md');
    const skillText = readFileSync(skillPath, 'utf8').replace(/\r?\n/g, '\r\n');
    writeFileSync(skillPath, skillText);

    const result = runNodeScript('scripts/validate.mjs', fixtureRoot);

    assert.equal(result.status, 0, result.stdout + result.stderr);
  } finally {
    rmSync(fixtureRoot, { recursive: true, force: true });
  }
});

test('skill index generator is idempotent on Windows paths', () => {
  const fixtureRoot = copyRepoFixture();
  const skillsPath = join(fixtureRoot, 'SKILLS.md');
  const before = readFileSync(skillsPath, 'utf8');

  try {
    const result = runNodeScript('scripts/generate-skills-md.mjs', fixtureRoot);

    assert.equal(result.status, 0, result.stdout + result.stderr);
    assert.equal(normalizeEol(readFileSync(skillsPath, 'utf8')), normalizeEol(before));
  } finally {
    rmSync(fixtureRoot, { recursive: true, force: true });
  }
});

test('Codex generator handles folded descriptions and removes stale skill metadata', () => {
  const fixtureRoot = copyRepoFixture();
  const skillDir = join(fixtureRoot, 'juristi/skills/codex-generator-test');
  const skillPath = join(skillDir, 'SKILL.md');
  const openAIYamlPath = join(skillDir, 'agents/openai.yaml');

  try {
    mkdirSync(skillDir, { recursive: true });
    writeFileSync(
      skillPath,
      [
        '---',
        'name: codex-generator-test',
        'description: >-',
        '  Tarkistaa oik.ai-lahteista, etta Codex metadata kuvaa',
        '  taitetun kuvauksen oikein.',
        '---',
        '',
        'Kayta oik.ai-lahteita.',
        '',
      ].join('\n'),
    );

    let result = runNodeScript('scripts/generate-codex.mjs', fixtureRoot);

    assert.equal(result.status, 0, result.stdout + result.stderr);
    assert.equal(existsSync(openAIYamlPath), true);

    const generated = readFileSync(openAIYamlPath, 'utf8');
    assert.match(generated, /short_description:\s+"Tarkistaa oik\.ai-lahteista/);
    assert.doesNotMatch(generated, /short_description:\s+">-"/);

    writeFileSync(
      skillPath,
      [
        '---',
        'name: codex-generator-test',
        'description: Ei tarvitse MCP-tyokaluja.',
        '---',
        '',
        'Paikallinen testiskill.',
        '',
      ].join('\n'),
    );

    result = runNodeScript('scripts/generate-codex.mjs', fixtureRoot);

    assert.equal(result.status, 0, result.stdout + result.stderr);
    assert.equal(existsSync(openAIYamlPath), false);
  } finally {
    rmSync(fixtureRoot, { recursive: true, force: true });
  }
});

test('Codex generator removes generated sidecars from orphaned skill directories', () => {
  const fixtureRoot = copyRepoFixture();
  const skillDir = join(fixtureRoot, 'juristi/skills/codex-orphan-test');
  const agentsDir = join(skillDir, 'agents');
  const openAIYamlPath = join(agentsDir, 'openai.yaml');

  try {
    mkdirSync(agentsDir, { recursive: true });
    writeFileSync(
      openAIYamlPath,
      [
        '# Generated by scripts/generate-codex.mjs. Do not edit by hand.',
        'interface:',
        '  display_name: "codex-orphan-test"',
        '',
      ].join('\n'),
    );

    const result = runNodeScript('scripts/generate-codex.mjs', fixtureRoot);

    assert.equal(result.status, 0, result.stdout + result.stderr);
    assert.equal(existsSync(openAIYamlPath), false);
  } finally {
    rmSync(fixtureRoot, { recursive: true, force: true });
  }
});
