#!/usr/bin/env node
// Generoi Codex-yhteensopivat manifestit olemassa olevasta Claude-markkinapaikasta.
// Aja: node scripts/generate-codex.mjs
//
// Lähde pysyy edelleen .claude-plugin/marketplace.json:ssa ja kunkin plugarin
// .claude-plugin/plugin.json:ssa. Tämä skripti kirjoittaa:
//  - .agents/plugins/marketplace.json
//  - <plugari>/.codex-plugin/plugin.json
//  - <plugari>/skills/<skill>/agents/openai.yaml

import {
  existsSync,
  mkdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, join } from 'node:path';

import {
  MARKETPLACE_DISPLAY_NAME,
  MARKETPLACE_NAME,
  REPOSITORY,
  ROOT,
  listDirs,
  oneLine,
  parseFrontmatter,
  readJSON as readJSONFile,
  truncate,
} from './lib.mjs';

const CATEGORY = 'Legal';

function readJSON(path) {
  return readJSONFile(join(ROOT, path));
}

function writeJSON(path, value) {
  const fullPath = join(ROOT, path);
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, `${JSON.stringify(value, null, 2)}\n`);
}

function writeText(path, value) {
  const fullPath = join(ROOT, path);
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, value);
}

function serverMapFromClaudeMcp(path) {
  const value = readJSON(path);
  return value.mcpServers || value.mcp_servers || value;
}

function readSkillMetadata(skillText, fallbackName) {
  const { values } = parseFrontmatter(skillText);
  const name = values.name || fallbackName;
  return { name, description: values.description || name };
}

// Codexin työkaluriippuvuudet päätellään SKILL.md-tekstistä näillä säännöillä.
// Uusi MCP-palvelin tai poikkeus: lisää rivi tähän tauluun — itse
// tunnistuslogiikkaa ei tarvitse muokata.
const DEPENDENCY_RULES = [
  {
    server: 'oik-ai',
    keywords: [
      'oik.ai',
      'finlex-mcp',
      'oikeustutkimus',
      'hankintalaki',
      'osakeyhtiölaki',
      'osakeyhtiolaki',
      'oyl ',
      'oiktl',
      'tarkista laki lähteestä',
      'tarkista laki lahteesta',
    ],
    // suomen-kieli mainitsee oikeuslähteet vain esimerkkinä — ei MCP-tarvetta.
    skipSkills: ['juristi/skills/suomen-kieli'],
  },
  {
    server: 'adeu',
    keywords: ['adeu'],
    skipSkills: [],
  },
  {
    server: 'eu-ai-act',
    keywords: ['eu ai act', 'euaiact', 'tekoälyasetuksen', 'tekoalyasetuksen'],
    skipSkills: [],
  },
];

function detectSkillDependencies(skillText, serverNames, skillPath) {
  const text = skillText.toLocaleLowerCase('fi-FI');
  return DEPENDENCY_RULES
    .filter((rule) =>
      serverNames.includes(rule.server) &&
      !rule.skipSkills.includes(skillPath) &&
      rule.keywords.some((keyword) => text.includes(keyword)))
    .map((rule) => rule.server);
}

function yamlQuote(value) {
  return `"${String(value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, '\\n')}"`;
}

// Riippuvuuskuvaus johdetaan plugarin .mcp.json-palvelinmäärittelystä
// (ensimmäinen virke), jotta kuvauksella on yksi lähde eikä generaattoriin
// kerry palvelinkohtaisia vakiotekstejä.
function firstSentence(text) {
  const match = text.match(/^.*?[.!?](?=\s|$)/);
  return match ? match[0] : text;
}

function dependencyDescription(name, server) {
  const source = oneLine(server.description || server.title || name);
  return truncate(firstSentence(source), 160);
}

function renderOpenAIYaml(dependencies, serverMap, skillMetadata) {
  const lines = [
    '# Generated by scripts/generate-codex.mjs. Do not edit by hand.',
    'interface:',
    `  display_name: ${yamlQuote(skillMetadata.name)}`,
    `  short_description: ${yamlQuote(truncate(skillMetadata.description, 160))}`,
    '',
    'dependencies:',
    '  tools:',
  ];

  for (const name of dependencies) {
    const server = serverMap[name];
    lines.push('    - type: "mcp"');
    lines.push(`      value: ${yamlQuote(name)}`);
    lines.push(`      description: ${yamlQuote(dependencyDescription(name, server))}`);

    if (server.url) {
      lines.push('      transport: "streamable_http"');
      lines.push(`      url: ${yamlQuote(server.url)}`);
    } else if (server.command) {
      lines.push('      transport: "stdio"');
      lines.push(`      command: ${yamlQuote(server.command)}`);
      if (Array.isArray(server.args) && server.args.length > 0) {
        lines.push('      args:');
        for (const arg of server.args) {
          lines.push(`        - ${yamlQuote(arg)}`);
        }
      }
    }
  }

  return `${lines.join('\n')}\n`;
}

function writeSkillDependencyMetadata(pluginRoot, serverMap) {
  const serverNames = Object.keys(serverMap);
  const skillsDir = join(ROOT, pluginRoot, 'skills');

  for (const skillDir of listDirs(skillsDir)) {
    const skillName = basename(skillDir);
    const openAIYaml = `${pluginRoot}/skills/${skillName}/agents/openai.yaml`;
    const skillMd = join(skillDir, 'SKILL.md');
    if (!existsSync(skillMd)) {
      removeGeneratedText(openAIYaml);
      continue;
    }

    const skillText = readFileSync(skillMd, 'utf8');
    const skillPath = `${pluginRoot}/skills/${skillName}`;
    const dependencies = detectSkillDependencies(skillText, serverNames, skillPath);

    if (dependencies.length === 0) {
      removeGeneratedText(openAIYaml);
      continue;
    }

    const skillMetadata = readSkillMetadata(skillText, skillName);
    writeText(
      openAIYaml,
      renderOpenAIYaml(dependencies, serverMap, skillMetadata),
    );
  }
}

function removeGeneratedText(path) {
  const fullPath = join(ROOT, path);
  if (!existsSync(fullPath)) return;
  const text = readFileSync(fullPath, 'utf8');
  if (!text.startsWith('# Generated by scripts/generate-codex.mjs.')) return;
  unlinkSync(fullPath);
}

function removeGeneratedSkillDependencyMetadata(pluginRoot) {
  const skillsDir = join(ROOT, pluginRoot, 'skills');

  for (const skillDir of listDirs(skillsDir)) {
    const skillName = basename(skillDir);
    removeGeneratedText(`${pluginRoot}/skills/${skillName}/agents/openai.yaml`);
  }
}

const marketplace = readJSON('.claude-plugin/marketplace.json');

const codexMarketplace = {
  name: MARKETPLACE_NAME,
  interface: {
    displayName: MARKETPLACE_DISPLAY_NAME,
  },
  plugins: [],
};

for (const entry of marketplace.plugins) {
  const pluginRoot = entry.source.replace(/^\.\//, '');
  const claudeManifest = readJSON(`${pluginRoot}/.claude-plugin/plugin.json`);
  const hasMcp = existsSync(join(ROOT, pluginRoot, '.mcp.json'));
  const serverMap = hasMcp ? serverMapFromClaudeMcp(`${pluginRoot}/.mcp.json`) : null;

  const codexManifest = {
    name: claudeManifest.name,
    version: claudeManifest.version,
    description: claudeManifest.description,
    author: claudeManifest.author,
    homepage: `${REPOSITORY}/tree/main/${pluginRoot}`,
    repository: REPOSITORY,
    license: 'MIT',
    keywords: ['legal', 'finland', 'finnish-law', entry.name],
    skills: './skills/',
    interface: {
      displayName: entry.displayName || entry.name,
      shortDescription: truncate(claudeManifest.description, 160),
      longDescription: entry.description || claudeManifest.description,
      developerName: entry.author?.name || claudeManifest.author?.name || marketplace.owner?.name,
      category: CATEGORY,
      capabilities: hasMcp ? ['Skills', 'MCP'] : ['Skills'],
      defaultPrompt: [
        truncate(`Käytä ${entry.displayName || entry.name} -plugaria Suomen oikeuden tehtävään.`, 120),
      ],
    },
  };

  if (hasMcp) {
    codexManifest.mcpServers = './.mcp.json';
    const staleCodexMcpPath = join(ROOT, pluginRoot, '.codex-plugin/mcp.json');
    if (existsSync(staleCodexMcpPath)) {
      unlinkSync(staleCodexMcpPath);
    }
    writeSkillDependencyMetadata(pluginRoot, serverMap);
  } else {
    removeGeneratedSkillDependencyMetadata(pluginRoot);
  }

  writeJSON(`${pluginRoot}/.codex-plugin/plugin.json`, codexManifest);

  codexMarketplace.plugins.push({
    name: entry.name,
    source: {
      source: 'local',
      path: entry.source,
    },
    policy: {
      installation: 'AVAILABLE',
      authentication: 'ON_INSTALL',
    },
    category: CATEGORY,
  });
}

writeJSON('.agents/plugins/marketplace.json', codexMarketplace);
console.log(`Codex-manifestit generoitu: ${codexMarketplace.plugins.length} plugaria.`);
